/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces.new'
import { Route as WorkspacesCodeRouteImport } from './routes/workspaces.$code'
import { Route as WorkspacesCodeIndexRouteImport } from './routes/workspaces.$code.index'
import { Route as WorkspacesCodeTeamRouteImport } from './routes/workspaces.$code.team'
import { Route as WorkspacesCodeRoadmapRouteImport } from './routes/workspaces.$code.roadmap'
import { Route as WorkspacesCodeRisksRouteImport } from './routes/workspaces.$code.risks'
import { Route as WorkspacesCodeRetrospectiveRouteImport } from './routes/workspaces.$code.retrospective'
import { Route as WorkspacesCodeDocumentsRouteImport } from './routes/workspaces.$code.documents'
import { Route as WorkspacesCodeDashboardRouteImport } from './routes/workspaces.$code.dashboard'
import { Route as WorkspacesCodeBoardRouteImport } from './routes/workspaces.$code.board'
import { Route as WorkspacesCodeBacklogRouteImport } from './routes/workspaces.$code.backlog'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesCodeRoute = WorkspacesCodeRouteImport.update({
  id: '/workspaces/$code',
  path: '/workspaces/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesCodeIndexRoute = WorkspacesCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeTeamRoute = WorkspacesCodeTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeRoadmapRoute = WorkspacesCodeRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeRisksRoute = WorkspacesCodeRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeRetrospectiveRoute =
  WorkspacesCodeRetrospectiveRouteImport.update({
    id: '/retrospective',
    path: '/retrospective',
    getParentRoute: () => WorkspacesCodeRoute,
  } as any)
const WorkspacesCodeDocumentsRoute = WorkspacesCodeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeDashboardRoute = WorkspacesCodeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeBoardRoute = WorkspacesCodeBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)
const WorkspacesCodeBacklogRoute = WorkspacesCodeBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => WorkspacesCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces/$code': typeof WorkspacesCodeRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/$code/backlog': typeof WorkspacesCodeBacklogRoute
  '/workspaces/$code/board': typeof WorkspacesCodeBoardRoute
  '/workspaces/$code/dashboard': typeof WorkspacesCodeDashboardRoute
  '/workspaces/$code/documents': typeof WorkspacesCodeDocumentsRoute
  '/workspaces/$code/retrospective': typeof WorkspacesCodeRetrospectiveRoute
  '/workspaces/$code/risks': typeof WorkspacesCodeRisksRoute
  '/workspaces/$code/roadmap': typeof WorkspacesCodeRoadmapRoute
  '/workspaces/$code/team': typeof WorkspacesCodeTeamRoute
  '/workspaces/$code/': typeof WorkspacesCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/$code/backlog': typeof WorkspacesCodeBacklogRoute
  '/workspaces/$code/board': typeof WorkspacesCodeBoardRoute
  '/workspaces/$code/dashboard': typeof WorkspacesCodeDashboardRoute
  '/workspaces/$code/documents': typeof WorkspacesCodeDocumentsRoute
  '/workspaces/$code/retrospective': typeof WorkspacesCodeRetrospectiveRoute
  '/workspaces/$code/risks': typeof WorkspacesCodeRisksRoute
  '/workspaces/$code/roadmap': typeof WorkspacesCodeRoadmapRoute
  '/workspaces/$code/team': typeof WorkspacesCodeTeamRoute
  '/workspaces/$code': typeof WorkspacesCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces/$code': typeof WorkspacesCodeRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/$code/backlog': typeof WorkspacesCodeBacklogRoute
  '/workspaces/$code/board': typeof WorkspacesCodeBoardRoute
  '/workspaces/$code/dashboard': typeof WorkspacesCodeDashboardRoute
  '/workspaces/$code/documents': typeof WorkspacesCodeDocumentsRoute
  '/workspaces/$code/retrospective': typeof WorkspacesCodeRetrospectiveRoute
  '/workspaces/$code/risks': typeof WorkspacesCodeRisksRoute
  '/workspaces/$code/roadmap': typeof WorkspacesCodeRoadmapRoute
  '/workspaces/$code/team': typeof WorkspacesCodeTeamRoute
  '/workspaces/$code/': typeof WorkspacesCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces/$code'
    | '/workspaces/new'
    | '/workspaces/$code/backlog'
    | '/workspaces/$code/board'
    | '/workspaces/$code/dashboard'
    | '/workspaces/$code/documents'
    | '/workspaces/$code/retrospective'
    | '/workspaces/$code/risks'
    | '/workspaces/$code/roadmap'
    | '/workspaces/$code/team'
    | '/workspaces/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspaces/new'
    | '/workspaces/$code/backlog'
    | '/workspaces/$code/board'
    | '/workspaces/$code/dashboard'
    | '/workspaces/$code/documents'
    | '/workspaces/$code/retrospective'
    | '/workspaces/$code/risks'
    | '/workspaces/$code/roadmap'
    | '/workspaces/$code/team'
    | '/workspaces/$code'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/workspaces/$code'
    | '/workspaces/new'
    | '/workspaces/$code/backlog'
    | '/workspaces/$code/board'
    | '/workspaces/$code/dashboard'
    | '/workspaces/$code/documents'
    | '/workspaces/$code/retrospective'
    | '/workspaces/$code/risks'
    | '/workspaces/$code/roadmap'
    | '/workspaces/$code/team'
    | '/workspaces/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WorkspacesCodeRoute: typeof WorkspacesCodeRouteWithChildren
  WorkspacesNewRoute: typeof WorkspacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$code': {
      id: '/workspaces/$code'
      path: '/workspaces/$code'
      fullPath: '/workspaces/$code'
      preLoaderRoute: typeof WorkspacesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$code/': {
      id: '/workspaces/$code/'
      path: '/'
      fullPath: '/workspaces/$code/'
      preLoaderRoute: typeof WorkspacesCodeIndexRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/team': {
      id: '/workspaces/$code/team'
      path: '/team'
      fullPath: '/workspaces/$code/team'
      preLoaderRoute: typeof WorkspacesCodeTeamRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/roadmap': {
      id: '/workspaces/$code/roadmap'
      path: '/roadmap'
      fullPath: '/workspaces/$code/roadmap'
      preLoaderRoute: typeof WorkspacesCodeRoadmapRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/risks': {
      id: '/workspaces/$code/risks'
      path: '/risks'
      fullPath: '/workspaces/$code/risks'
      preLoaderRoute: typeof WorkspacesCodeRisksRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/retrospective': {
      id: '/workspaces/$code/retrospective'
      path: '/retrospective'
      fullPath: '/workspaces/$code/retrospective'
      preLoaderRoute: typeof WorkspacesCodeRetrospectiveRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/documents': {
      id: '/workspaces/$code/documents'
      path: '/documents'
      fullPath: '/workspaces/$code/documents'
      preLoaderRoute: typeof WorkspacesCodeDocumentsRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/dashboard': {
      id: '/workspaces/$code/dashboard'
      path: '/dashboard'
      fullPath: '/workspaces/$code/dashboard'
      preLoaderRoute: typeof WorkspacesCodeDashboardRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/board': {
      id: '/workspaces/$code/board'
      path: '/board'
      fullPath: '/workspaces/$code/board'
      preLoaderRoute: typeof WorkspacesCodeBoardRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
    '/workspaces/$code/backlog': {
      id: '/workspaces/$code/backlog'
      path: '/backlog'
      fullPath: '/workspaces/$code/backlog'
      preLoaderRoute: typeof WorkspacesCodeBacklogRouteImport
      parentRoute: typeof WorkspacesCodeRoute
    }
  }
}

interface WorkspacesCodeRouteChildren {
  WorkspacesCodeBacklogRoute: typeof WorkspacesCodeBacklogRoute
  WorkspacesCodeBoardRoute: typeof WorkspacesCodeBoardRoute
  WorkspacesCodeDashboardRoute: typeof WorkspacesCodeDashboardRoute
  WorkspacesCodeDocumentsRoute: typeof WorkspacesCodeDocumentsRoute
  WorkspacesCodeRetrospectiveRoute: typeof WorkspacesCodeRetrospectiveRoute
  WorkspacesCodeRisksRoute: typeof WorkspacesCodeRisksRoute
  WorkspacesCodeRoadmapRoute: typeof WorkspacesCodeRoadmapRoute
  WorkspacesCodeTeamRoute: typeof WorkspacesCodeTeamRoute
  WorkspacesCodeIndexRoute: typeof WorkspacesCodeIndexRoute
}

const WorkspacesCodeRouteChildren: WorkspacesCodeRouteChildren = {
  WorkspacesCodeBacklogRoute: WorkspacesCodeBacklogRoute,
  WorkspacesCodeBoardRoute: WorkspacesCodeBoardRoute,
  WorkspacesCodeDashboardRoute: WorkspacesCodeDashboardRoute,
  WorkspacesCodeDocumentsRoute: WorkspacesCodeDocumentsRoute,
  WorkspacesCodeRetrospectiveRoute: WorkspacesCodeRetrospectiveRoute,
  WorkspacesCodeRisksRoute: WorkspacesCodeRisksRoute,
  WorkspacesCodeRoadmapRoute: WorkspacesCodeRoadmapRoute,
  WorkspacesCodeTeamRoute: WorkspacesCodeTeamRoute,
  WorkspacesCodeIndexRoute: WorkspacesCodeIndexRoute,
}

const WorkspacesCodeRouteWithChildren = WorkspacesCodeRoute._addFileChildren(
  WorkspacesCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WorkspacesCodeRoute: WorkspacesCodeRouteWithChildren,
  WorkspacesNewRoute: WorkspacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
